### ISSUE TITLE
closed AMQP 1.0 consumer after idle timeout is not restored

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/ditto#414] opened 2019-05-24 09:36 UTC
Azure Service Bus has the behavior that idle AMQP 1.0 links are closed after ~10 minutes of idle timeout.

We get following log message and afterwards the AMQP 1.0 Azure Service Bus connection is in a strange state:
```
Consumer <org.apache.qpid.jms.JmsMessageConsumer@3b8f105d> closed due to JmsConnectionRemotelyClosedException: The connection was inactive for more than the allowed 120000 milliseconds and is closed by container '...'. [condition = amqp:connection:forced]
```

"Strange" because: after that message we get following messages:
```
May 23rd 2019, 06:56:14.973 Session closed: org.apache.qpid.jms.JmsSession@3230bc47 - Unknown error from remote peer
May 23rd 2019, 06:56:14.975 Connection interrupted: amqps://<...>.servicebus.windows.net:5671?amqp.saslMechanisms=PLAIN&transport.trustAll=true&transport.verifyHost=false
May 23rd 2019, 06:56:16.229 Connection restored: amqps://<...>.servicebus.windows.net:5671?amqp.saslMechanisms=PLAIN&transport.trustAll=true&transport.verifyHost=false
```

The last 2 messages repeat themselves each second.

We could/should react on `org.eclipse.ditto.services.connectivity.messaging.amqp.AmqpClientActor.StatusReportingListener#onConsumerClosed` and restore the connection.

What also can be seen: the default JMS client timeout seems to be 120s (see error message above) - we should increase that to at least 5 min.
Azure Service Bus' timeout seems to be ~9-11 minutes.

I'm not sure why this only happens on Service Bus - as for Eclipse Hono we also have consumers which are "idling" 2 minutes. Maybe the AMQP endpoint does however keep them open infinitely.

@kaizimmerm : could you please have a look on this?

**Comment by kaizimmerm** [comment] 2019-06-18 17:35
@thjaeckle I struggle to reproduce this. My Ditto installation never shows these messages. Even after days of idle time it always reacts promptly to inbound messages so I assume the consumers are alive and well.

I tried different connection setups (all with Azure Service Bus standard plan) but none showed the described behaviour. Tried:
* With or without `failoverEnabled`
* With or without 
```json
"specificConfig": {
        "amqp.idleTimeout": 120000
      }
```
* I even set the client idleTimeout to 20 minutes once to force this, but even then I only got a shutdown of the producer from the server.

Can you give me a bit more input that might help to track this down, e.g. how your connection has been setup?

**Comment by kaizimmerm** [comment] 2019-06-24 06:59
@dguggemos thx for putting in the work. However, I think it will be hard to provide a fix if we cannot reproduce this with Ditto. Do you happen to be successful in that regard as well?

I will continue to reproduce this in Ditto so I am grateful for hints.

btw. did you use Basic or Standard SB plan for your test?

**Comment by kaizimmerm** [comment] 2019-06-25 07:01
@dguggemos @thjaeckle I fear I am running out of ideas how to reproduce this.

I ran Ditto 0.9.0-M2 with a local setup on my Laptop as well as in k8s on Azure over hours with connections to SB instances in West Europe both on Basic as well as Standard plan. 

I had use cases both with producers as well as consumers running on both sides, i.e. Ditto target+source as well as my two examples with [consumer](https://github.com/eclipse/ditto-examples/blob/master/azure/azure-servicebus-amqp10/src/main/java/org/eclipse/ditto/examples/azure/MessageConsumer.java) and [producer](https://github.com/eclipse/ditto-examples/blob/master/azure/azure-servicebus-amqp10/src/main/java/org/eclipse/ditto/examples/azure/MessageProducer.java).

Never any problems as described by you.

Pls let me know if you managed to reproduce this with Ditto and how.

Kai

**Comment by dguggemos** [comment] 2019-07-02 09:13
@kaizimmerm I made some progress regarding this issue. I could not reproduce the problem, but I think I understand what happens now. For some reasons the existing AMQP session is unexpectedly closed by the Azure Service Bus, but the connection stays alive. And this is probably what the "LinkTracker" observes (a connection without any session/consumer/producer) and it closes this connection. This seem to happen randomly, I could not see any pattern. Any way, PR #434 handles the closing of the session and recreates it (and all associated consumers and producers).

**Comment by dguggemos** [comment] 2019-07-23 12:51
The recovery of the sessions seems to work and no more issues have been reported since then.

**Closed by dguggemos** 2019-07-23 12:51 UTC
Labels: bug
